
# Agenda for Meeting 

Date: `r format(Sys.time(), '%d %B, %Y')`

.grey_Inedit[
1. Coordination and alignement with WP 4.3-4.4
1. Literature and Background on Additive manufacturing / Recycling / Sustainability
1. Printability test on Virgin material for calibration purposes
1. Iterative technical improvement of printing process
1. Definition of the scope of plastic wastes according printability
1. Experimental research design to test quality on virgin and recycled objects
1. Technical development of smart collector to collect plastic waste
1. .large.bg-yellow[**Validation and consolidation of network of the local actors**]
1. Validation Demonstrator for INEDIT stakeholders (according KPI's?)
      ]   


### Main Goal:

- To establish a local netwotk in order to collect and recycled plastic waste 


---
class: middle
## Validation and consolidation of network of the local actors

.Large[**Work in progress**]

.center[
<iframe src="https://giphy.com/embed/l0K4hO8mVvq8Oygjm" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/topshelfrecords-clique-top-shelf-records-l0K4hO8mVvq8Oygjm"></a></p>

]