---
title: "index"
output:
  html_document:
    self_contained: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmlwidgets)
library(slickR)

newlogo <- "https://jeroen.github.io/images/Rlogo.png"
images=rep(newlogo,11)
img <- magick::image_read(images) %>%
  magick::image_montage(tile = '3')

```



```{r, include=FALSE, eval=FALSE}
# Packages
library(magick)
library(here)
library(tidyverse)


# Inspiration: https://stackoverflow.com/questions/62536020/r-magick-process-multiple-files
convert_img <- function(infile, outpath, nombre="Test", ID.min=1, ID.max =  sum (1, max(cantidad)) , topspace=200){ 
   require(magick)
   if(!file.exists(infile)) return("file does not exist")
   
   print(paste0("Load ", infile, " ..."))
   read0 <- image_read(infile, strip = TRUE)
   basename <- basename(infile)
   basename2 <- tools::file_path_sans_ext(basename)
   basename3 <- Sys.Date() %>%  paste(nombre, ID.min, ID.max, sep = "-" )
    
   
   print(paste0("Resize ", basename, " ..."))
   read2000 <- image_resize(read0, "x2000")
   #read4300 <- image_resize(read0, "4300x4300")
   #read4000 <- image_resize(read0, "4000x4000")
   
   #print(paste0("Extent ", basename, " ..."))
   #read5400 <- image_extent(read4300, paste0("4500x", 5400-2*topspace), gravity = "North")
   #read5400 <- image_extent(read5400, "4500x5400", gravity = "Center")
   #read4050 <- image_extent(read4000, "4500x4050")
   #print(paste0("Speicher ", basename, " ..."))
   
   ## Exporting the phtos
   image_write(read2000 , path= file.path(outpath, paste0(basename2, ".jpg")), format =  "jpg", quality = 75)
   #image_write(read4000 , file.path(outpath, paste0(basename2, "4000.png")))
   #image_write(read5400 , file.path(outpath, paste0(basename2,"5400.png")))
   #image_write(read4050 , file.path(outpath, paste0(basename2,"4050.png")))
   gc(full=TRUE)
}


# Identifying the photos files
files <- list.files(path= here("images"), pattern = ".jpg", full.names = TRUE)
cantidad <- length(files)


## Exporting the images
files %>% map(convert_img, 
              outpath= here("images", "Finals"),  
              nombre="Test", 
              ID.min=1 
              )



```

## 6.4 3D printing of recycled plastic demonstrator [TL: UL. Participants: CROWD, TTPSC]


```{r}
slickR::slickR(
    list.files("images/Finals",full.names = TRUE,pattern = 'jpg'),
    height = 500,
    width = 1500) +
  slickR::settings(autoplay = TRUE, autoplaySpeed = 8000)
```

